import Head from "next/head";
import Footer from "./footer";
import Maps from "./maps";
import Navbar from "./navbar";


export default function Layout({children, title}){

    return(
       <>
        <Head>
            <title>{title}</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar/>

        {children}

        <Maps/>
        <Footer/>
       </> 
    )

}
